# Generated by Django 3.1.1 on 2020-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartPlace', models.CharField(max_length=100)),
                ('EndPlace', models.CharField(max_length=100)),
                ('OrderInformation', models.CharField(max_length=100)),
                ('EstimatedDate', models.DateField()),
                ('EstimatedTime', models.TimeField()),
                ('Price', models.FloatField()),
                ('OrderName', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('OrderStatus', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
