# Generated by Django 3.1.1 on 2020-12-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartPlace', models.CharField(max_length=100, verbose_name='起始地点')),
                ('EndPlace', models.CharField(max_length=100, verbose_name='目的地点')),
                ('X_StudentNumber', models.CharField(max_length=13, verbose_name='下单者学号')),
                ('J_StudentNumber', models.CharField(default='null', max_length=13, verbose_name='接单者学号')),
                ('EstimatedDate', models.DateField(verbose_name='期望日期')),
                ('EstimatedTime', models.TimeField(verbose_name='期望时间')),
                ('OrderDate', models.DateField(auto_now_add=True, verbose_name='下单日期')),
                ('OrderTime', models.TimeField(auto_now_add=True, verbose_name='下单时间')),
                ('Price', models.FloatField(verbose_name='价格')),
                ('OrderName', models.CharField(max_length=20, verbose_name='订单名称')),
                ('OrderInformation', models.CharField(max_length=100, verbose_name='订单信息')),
                ('X_PhoneNumber', models.CharField(max_length=11, verbose_name='下单者电话号码')),
                ('J_PhoneNumber', models.CharField(default='null', max_length=11, verbose_name='接单者电话号码')),
                ('OrderStatus', models.CharField(default='未接受', max_length=6, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
    ]
