# Generated by Django 3.1.1 on 2020-12-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
    ]
