# Generated by Django 3.1.1 on 2020-12-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(default='未接受', max_length=6, verbose_name='订单状态'),
        ),
    ]
