# Generated by Django 3.1.1 on 2020-12-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0002_auto_20201201_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='EndPlace',
            field=models.CharField(max_length=100, verbose_name='目的地点'),
        ),
        migrations.AlterField(
            model_name='order',
            name='EstimatedDate',
            field=models.DateField(verbose_name='期望日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='EstimatedTime',
            field=models.TimeField(verbose_name='期望时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderInformation',
            field=models.CharField(max_length=100, verbose_name='订单信息'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderName',
            field=models.CharField(max_length=20, verbose_name='订单名称'),
        ),
        migrations.AlterField(
            model_name='order',
            name='PhoneNumber',
            field=models.CharField(max_length=11, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.FloatField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='StartPlace',
            field=models.CharField(max_length=100, verbose_name='起始地点'),
        ),
    ]
