# Generated by Django 3.1.1 on 2020-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0003_auto_20201201_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.IntegerField(default=0, verbose_name='订单状态'),
        ),
    ]
