# Generated by Django 3.1.1 on 2020-12-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0004_auto_20201201_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(default='未接受', max_length=6, verbose_name='订单状态'),
        ),
    ]
