# Generated by Django 3.1.1 on 2020-12-08 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0005_auto_20201208_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.date(2020, 12, 8), verbose_name='下单日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='OrderTime',
            field=models.TimeField(default=datetime.time(10, 43, 41, 166476), verbose_name='下单时间'),
        ),
    ]
