# Generated by Django 3.1.1 on 2020-12-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0006_auto_20201208_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(verbose_name='下单日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderTime',
            field=models.TimeField(verbose_name='下单时间'),
        ),
    ]
