# Generated by Django 3.1.1 on 2020-12-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order', '0007_auto_20201208_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(auto_now_add=True, verbose_name='下单日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderTime',
            field=models.TimeField(auto_now_add=True, verbose_name='下单时间'),
        ),
    ]
