# Generated by Django 3.1.1 on 2020-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10, null=True)),
                ('Password', models.CharField(max_length=20)),
                ('PhoneNumber', models.IntegerField()),
                ('StudentNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
