# Generated by Django 3.1.1 on 2020-11-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserName',
        ),
    ]
