# Generated by Django 3.1.1 on 2020-11-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='StudentNumber',
            field=models.CharField(max_length=20),
        ),
    ]
