# Generated by Django 3.1.1 on 2020-12-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0003_auto_20201106_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
